In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [5]:
test = pd.read_csv("test (1).csv")

# Drop non-feature columns
X = test.drop(columns=['id'])

# Fake target just for training demo (e.g., random classification with 3 classes)
y = np.random.randint(0, 3, size=len(X))  # 3 classes: 0, 1, 2

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Build a simple neural network
model = Sequential([
    Dense(32, activation='relu', input_shape=(X_scaled.shape[1],)),
    Dense(16, activation='relu'),
    Dense(3, activation='softmax')  # Output layer for 3-class classification
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train on dummy data
model.fit(X_scaled, y, epochs=10, batch_size=16)

# Predict using the same data
predictions = model.predict(X_scaled)
predicted_classes = np.argmax(predictions, axis=1)

# Save predictions
test['fake_prediction'] = predicted_classes
test[['id', 'fake_prediction']].to_csv("fake_predictions.csv", index=False)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3207 - loss: 1.1425
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4023 - loss: 1.0990
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4177 - loss: 1.0731
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4416 - loss: 1.0536
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4224 - loss: 1.0628
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4726 - loss: 1.0425
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4464 - loss: 1.0435
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4469 - loss: 1.0363
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5072 - loss: 1.0148
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4936 - loss: 1.0141
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [6]:
print(predictions)

[[0.27255663 0.50575626 0.22168706]
 [0.2353796  0.33338487 0.43123555]
 [0.21733493 0.24346349 0.5392017 ]
 ...
 [0.25195938 0.37610993 0.37193063]
 [0.28241798 0.3234839  0.3940982 ]
 [0.27873442 0.20431647 0.5169491 ]]
